# https://docs.github.com/en
# CI/CD and DevOps
# https://docs.github.com/en/pages
# Configuring a publishing source for your GitHub Pages site
# Publishing with a custom GitHub Actions workflow
# https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#creating-a-custom-github-actions-workflow-to-publish-your-site

# https://github.com/actions/upload-pages-artifact
# merge my nodejs build with the example at url above

name: Angular Build CI & Github Pages Deploy
on:
  push:
    branches:
      - deploy-ghp # this branch must be added to the list in settings / environments / github-pages
jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    name: CI Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test:ci
    - name: Build
      run: npm run build
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions: # add to fix err "Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable"
      id-token: write  # Add this line to allow requesting OIDC tokens
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
