# .github/workflows/calling-workflow.yml
name: Calling Workflow

on:
  push:
    branches:
      - [ "deploy-ghp" ]

jobs:
  trigger-called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Call another workflow
        uses: /home/runner/work/uklic/uklic/.github/workflows/called-workflow.yml
        with:
          greeting: 'Hello from Calling Workflow!'
